services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=/app/config/development.toml
      - PYTHMATA_PLUGIN_DIR=/app/plugins
      - PYTHMATA_INSTALL_PLUGIN_DEPS=true
    volumes:
      - ./backend:/app
      - ./config:/app/config
      - ./plugins:/app/plugins
    # Make scripts executable after container starts
    command: >
      bash -c "chmod +x /app/scripts/*.sh && /app/scripts/start.sh"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pythmata
      POSTGRES_USER: pythmata
      POSTGRES_PASSWORD: pythmata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
