[server]
host = "0.0.0.0"
port = 8000
debug = true

[database]
url = "postgresql+asyncpg://pythmata:pythmata@postgres:5432/pythmata"
pool_size = 5
max_overflow = 10

[redis]
url = "redis://redis:6379/0"
pool_size = 10

[rabbitmq]
url = "amqp://guest:guest@rabbitmq:5672/"
connection_attempts = 5
retry_delay = 5

[security]
secret_key = "development_secret_key"
algorithm = "HS256"
access_token_expire_minutes = 30

[process]
script_timeout = 30
max_instances = 1000
cleanup_interval = 3600
